### ISSUE TITLE
Proper working USB mapping

### ISSUE THREAD

**Issue by BillDH2k** [ahnaf2012/HP-Z440-OpenCore#1]
Hi, I started with your EFI and successfully installed Monterey. Made some changes and improvement. So I'm sharing a working Z440 USB maps, which again I modified based on partially working version from another contributor. This is a much simpler and cleaner approach (once you figure out how to do it!). Just load this kext, no other tools are required, including USBInjectAll.kext. 

With this particular map, all external ports are working, except the USB2 personality of the front bottom USB 3 connector (regular USB3 function is still working). Due to 15 ports limit, this port is spared in order for enable 1/2 of the internal USB 2 connector.  To use it, you would need to remove your current USB mapping tools, including USBInjectAll.kext. Just add this kext to OC. Try it, let me know if there is any issue.

Thanks!

[Z440-USBMap.kext.zip](https://github.com/ahnaf2012/HP-Z440-OpenCore/files/8448365/Z440-USBMap.kext.zip)

**Comment by ahnaf2012** [comment]
Sorry I was busy with school for the past few months. I will look into this and update the EFI.
